{% set name = "tsam" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsam-{{ version }}.tar.gz
  sha256: 53905dceea53e91b3bfce71bc794922fd1f395f9eadc0fe84448e21701373fef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >3.0
    - setuptools-git
    - pip
  run:
    - python >3.0
    - scikit-learn >=0.0
    - pandas >=0.18.1
    - numpy >=1.11.0
    - pyomo >=6.4.3
    - networkx
    - tqdm
    - highspy

test:
  imports:
    - tsam
  source_files:
    - .
  commands:
    - pytest -n auto test/
    - pip check
  requires:
    - pip
    - pytest-xdist

about:
  home: https://github.com/FZJ-IEK3-VSA/tsam
  summary: Time series aggregation module (tsam) to create typical periods
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://tsam.readthedocs.io/en/master/
  dev_url: https://github.com/FZJ-IEK3-VSA/tsam


extra:
  recipe-maintainers:
    - OfficialCodexplosive
    - maximilian-hoffmann
    - julian-belina
